export const UPDATE_FORM_EMAIL_REQUEST = "UPDATE_FORM_EMAIL_REQUEST";
export const UPDATE_FORM_EMAIL_SUCCESS = "UPDATE_FORM_EMAIL_SUCCESS";
export const UPDATE_FORM_EMAIL_FAILURE = "UPDATE_FORM_EMAIL_FAILURE";
export const SET_FORM_EMAIL = "SET_FORM_EMAIL";
