export const GET_ABOUT_PAGE = "GET_ABOUT_PAGE";
export const GET_ABOUT_PAGE_FAILURE = "GET_ABOUT_PAGE_FAILURE";
export const GET_ABOUT_PAGE_SUCCESS = "GET_ABOUT_PAGE_SUCCESS";
export const UPDATE_ABOUT_PAGE = "UPDATE_ABOUT_PAGE";
export const UPDATE_ABOUT_PAGE_FAILURE = "UPDATE_ABOUT_PAGE_FAILURE";
export const UPDATE_ABOUT_PAGE_SUCCESS = "UPDATE_ABOUT_PAGE_SUCCESS";
